AWSTemplateFormatVersion: '2010-09-09'
Description: Huntaze Video Processor - ECS/Fargate only

Parameters:
  Environment:
    Type: String
    Default: production
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for ECS tasks
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for ECS tasks
  
  DatabaseUrl:
    Type: String
    NoEcho: true
    Description: Database connection string
  
  ImageUri:
    Type: String
    Description: ECR image URI for the video processor container

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub huntaze-video-processor-${Environment}
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /huntaze/video-processor-${Environment}
      RetentionInDays: 30

  # IAM Role for ECS Task Execution
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub huntaze-video-processor-execution-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # IAM Role for Video Processor Task
  VideoProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub huntaze-video-processor-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: VideoProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::huntaze-videos-${Environment}/*
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:huntaze-video-processing-${Environment}
              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # ECS Task Definition
  VideoProcessorTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub huntaze-video-processor-${Environment}
      RequiresCompatibilities: [FARGATE]
      NetworkMode: awsvpc
      Cpu: '4096'
      Memory: '8192'
      EphemeralStorage:
        SizeInGiB: 100
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt VideoProcessorRole.Arn
      ContainerDefinitions:
        - Name: video-processor
          Image: !Ref ImageUri
          Essential: true
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: SQS_QUEUE_URL
              Value: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:huntaze-video-processing-${Environment}
            - Name: S3_BUCKET
              Value: !Sub huntaze-videos-${Environment}
            - Name: DATABASE_URL
              Value: !Ref DatabaseUrl
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # Security Group
  VideoProcessorSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for video processor
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # ECS Service (SQS Worker) - NO AUTO SCALING
  VideoProcessorService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub huntaze-video-processor-${Environment}
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref VideoProcessorTaskDef
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref VideoProcessorSG
          AssignPublicIp: ENABLED

Outputs:
  ECSClusterName:
    Description: Name of the ECS cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${AWS::StackName}-ECSCluster

  VideoProcessorServiceName:
    Description: Name of the video processor service
    Value: !Ref VideoProcessorService
    Export:
      Name: !Sub ${AWS::StackName}-VideoProcessorService
