AWSTemplateFormatVersion: '2010-09-09'
Description: Huntaze Video Processor - S3 and SQS only

Parameters:
  Environment:
    Type: String
    Default: production

Resources:
  # S3 Bucket for video storage
  VideoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub huntaze-videos-${Environment}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3600

  # SQS Queue for video processing
  VideoProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub huntaze-video-processing-${Environment}
      VisibilityTimeout: 900
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt VideoProcessingDLQ.Arn
        maxReceiveCount: 3

  # Dead Letter Queue
  VideoProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub huntaze-video-processing-${Environment}-dlq
      MessageRetentionPeriod: 1209600

Outputs:
  VideoBucketName:
    Description: Name of the video storage bucket
    Value: !Ref VideoBucket
    Export:
      Name: !Sub ${AWS::StackName}-VideoBucket

  VideoProcessingQueueUrl:
    Description: URL of the video processing queue
    Value: !Ref VideoProcessingQueue
    Export:
      Name: !Sub ${AWS::StackName}-VideoProcessingQueue
