# Percy configuration for visual regression testing
version: 2

# Take snapshots at multiple breakpoints
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet
    - 1280  # Desktop
    - 1920  # Wide desktop
  
  # Minimum height to capture full page
  min-height: 1024
  
  # Enable JavaScript for dynamic content
  enable-javascript: true
  
  # Wait for network idle before snapshot
  network-idle-timeout: 500

# Discovery settings
discovery:
  # Allowed hostnames for asset discovery
  allowed-hostnames:
    - localhost
    - '*.huntaze.com'
  
  # Network idle timeout during discovery
  network-idle-timeout: 500
  
  # Disable asset caching between snapshots
  disable-cache: false

# Static site configuration
static:
  # Build directory
  base-url: /
  
  # Files to snapshot
  files: '**/*.html'
  
  # Ignore patterns
  ignore:
    - '**/node_modules/**'
    - '**/.next/**'
    - '**/coverage/**'

# Test different theme states
storybook:
  # Additional snapshots for theme variations
  additional-snapshots:
    - suffix: ' - dark mode'
      execute: |
        document.documentElement.classList.add('dark-mode');
        document.documentElement.classList.add('theme-dark');
    
    - suffix: ' - light mode'
      execute: |
        document.documentElement.classList.remove('dark-mode');
        document.documentElement.classList.add('theme-light');
    
    - suffix: ' - AMOLED mode'
      execute: |
        document.documentElement.classList.add('dark-mode');
        document.documentElement.classList.add('amoled');
    
    - suffix: ' - colorblind safe'
      execute: |
        document.documentElement.classList.add('colorblind-safe');