version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing root deps for load test"
      - npm ci
  build:
    commands:
      - echo "Running ECS load test via scripts/of-load-test.js"
      - |
        node scripts/of-load-test.js \
          --action ${ACTION:-login} \
          --count ${COUNT:-10} \
          --concurrency ${CONCURRENCY:-5} \
          --cluster "$CLUSTER_ARN" \
          --task-def "$TASK_DEF_ARN" \
          --subnets "$SUBNETS" \
          --security-group "$SECURITY_GROUP" \
          --user-ids "$USER_IDS" || true
reports:
  LoadTestReport:
    files:
      - '**/*'
    base-directory: 'reports'
