[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://api.huntaze.com"
  NEXT_PUBLIC_APP_URL = "https://huntaze.com"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_51RxE912KbmGn7DBK56bX8wioig3vLUAGDKmjRScketMFKJrRYjlXWG81WJAn97opJWPd1XZVaI9VhNDejoBbvLJF00AyA6grdI"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://api.huntaze.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
