#!/bin/bash

# Quick commands to fix the webpack error
# "Cannot read properties of undefined (reading 'call')"

echo "🚀 Quick Fix Steps"
echo "=================="
echo ""
echo "The error is a webpack module resolution issue."
echo "Here are the steps to fix it:"
echo ""
echo "1️⃣ Clear Next.js cache:"
echo "   rm -rf .next"
echo ""
echo "2️⃣ Clear node_modules cache:"
echo "   rm -rf node_modules/.cache"
echo ""
echo "3️⃣ Restart dev server:"
echo "   npm run dev"
echo ""
echo "If that doesn't work, try a full rebuild:"
echo "   rm -rf .next node_modules/.cache"
echo "   npm run build"
echo "   npm run dev"
echo ""
echo "✅ Changes made:"
echo "   - Added Button.displayName to components/ui/button.tsx"
echo "   - This helps React DevTools and module resolution"
echo ""
