export const nf = new Intl.NumberFormat('en')
export const usd = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })
export const dt = new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' })
export const rtf = new Intl.RelativeTimeFormat('en', { numeric: 'auto' })
export const list = new Intl.ListFormat('en', { style: 'short', type: 'conjunction' })
export const plural = new Intl.PluralRules('en')
