export declare const SMART_ONBOARDING_TABLES: {
    readonly USER_PROFILES: "smart_onboarding_user_profiles";
    readonly ONBOARDING_JOURNEYS: "smart_onboarding_journeys";
    readonly ONBOARDING_STEPS: "smart_onboarding_steps";
    readonly LEARNING_PATHS: "smart_onboarding_learning_paths";
    readonly BEHAVIOR_EVENTS: "smart_onboarding_behavior_events";
    readonly INTERACTION_DATA: "smart_onboarding_interaction_data";
    readonly ENGAGEMENT_METRICS: "smart_onboarding_engagement_metrics";
    readonly STRUGGLE_INDICATORS: "smart_onboarding_struggle_indicators";
    readonly USER_PERSONAS: "smart_onboarding_user_personas";
    readonly PREDICTION_MODELS: "smart_onboarding_prediction_models";
    readonly MODEL_TRAINING_DATA: "smart_onboarding_model_training_data";
    readonly SUCCESS_PREDICTIONS: "smart_onboarding_success_predictions";
    readonly INTERVENTIONS: "smart_onboarding_interventions";
    readonly INTERVENTION_OUTCOMES: "smart_onboarding_intervention_outcomes";
    readonly HELP_CONTENT: "smart_onboarding_help_content";
    readonly ESCALATION_TICKETS: "smart_onboarding_escalation_tickets";
    readonly CONTENT_VARIATIONS: "smart_onboarding_content_variations";
    readonly PERSONALIZED_CONTENT: "smart_onboarding_personalized_content";
    readonly CONTENT_RECOMMENDATIONS: "smart_onboarding_content_recommendations";
    readonly ADAPTATION_HISTORY: "smart_onboarding_adaptation_history";
    readonly BEHAVIORAL_INSIGHTS: "smart_onboarding_behavioral_insights";
    readonly PATH_PERFORMANCE: "smart_onboarding_path_performance";
    readonly EXPERIMENT_RESULTS: "smart_onboarding_experiment_results";
    readonly SYSTEM_METRICS: "smart_onboarding_system_metrics";
};
export declare const DATABASE_INDEXES: {
    readonly BEHAVIOR_EVENTS_USER_TIME: "idx_behavior_events_user_timestamp";
    readonly ENGAGEMENT_METRICS_USER_TIME: "idx_engagement_metrics_user_timestamp";
    readonly INTERVENTIONS_USER_STATUS: "idx_interventions_user_status";
    readonly JOURNEYS_USER_STATUS: "idx_journeys_user_status";
    readonly PREDICTIONS_USER_TIME: "idx_predictions_user_timestamp";
    readonly PERSONAS_USER_CONFIDENCE: "idx_personas_user_confidence";
    readonly PATH_PERFORMANCE_TIME: "idx_path_performance_timestamp";
    readonly SYSTEM_METRICS_TIME: "idx_system_metrics_timestamp";
};
export declare const CACHE_KEYS: {
    readonly USER_PROFILE: (userId: string) => string;
    readonly USER_JOURNEY: (userId: string) => string;
    readonly USER_PERSONA: (userId: string) => string;
    readonly ENGAGEMENT_SCORE: (userId: string) => string;
    readonly LEARNING_PATH: (pathId: string) => string;
    readonly STEP_CONTENT: (stepId: string) => string;
    readonly CONTENT_RECOMMENDATIONS: (userId: string, stepId: string) => string;
    readonly MODEL_PREDICTIONS: (userId: string, modelType: string) => string;
    readonly SUCCESS_PREDICTION: (userId: string) => string;
    readonly SYSTEM_METRICS: "smart_onboarding:system_metrics";
    readonly ACTIVE_EXPERIMENTS: "smart_onboarding:active_experiments";
    readonly MODEL_PERFORMANCE: (modelId: string) => string;
};
export declare const CACHE_TTL: {
    readonly ENGAGEMENT_SCORE: 60;
    readonly BEHAVIOR_EVENTS: 300;
    readonly REAL_TIME_METRICS: 30;
    readonly USER_JOURNEY: 1800;
    readonly CONTENT_RECOMMENDATIONS: 900;
    readonly INTERVENTION_PLANS: 600;
    readonly USER_PROFILE: 3600;
    readonly USER_PERSONA: 7200;
    readonly LEARNING_PATH: 14400;
    readonly STEP_CONTENT: 21600;
    readonly MODEL_PREDICTIONS: 1800;
    readonly SUCCESS_PREDICTION: 3600;
    readonly MODEL_PERFORMANCE: 86400;
    readonly SYSTEM_METRICS: 300;
    readonly ACTIVE_EXPERIMENTS: 3600;
};
export declare const WEBSOCKET_EVENTS: {
    readonly JOURNEY_STARTED: "journey_started";
    readonly STEP_STARTED: "step_started";
    readonly STEP_COMPLETED: "step_completed";
    readonly JOURNEY_COMPLETED: "journey_completed";
    readonly JOURNEY_PAUSED: "journey_paused";
    readonly JOURNEY_RESUMED: "journey_resumed";
    readonly ENGAGEMENT_CHANGED: "engagement_changed";
    readonly ENGAGEMENT_ALERT: "engagement_alert";
    readonly STRUGGLE_DETECTED: "struggle_detected";
    readonly INTERVENTION_TRIGGERED: "intervention_triggered";
    readonly INTERVENTION_DELIVERED: "intervention_delivered";
    readonly INTERVENTION_COMPLETED: "intervention_completed";
    readonly HELP_REQUESTED: "help_requested";
    readonly CONTENT_ADAPTED: "content_adapted";
    readonly CONTENT_RECOMMENDATION: "content_recommendation";
    readonly PATH_OPTIMIZED: "path_optimized";
    readonly MODEL_UPDATED: "model_updated";
    readonly PERFORMANCE_ALERT: "performance_alert";
    readonly SYSTEM_HEALTH: "system_health";
    readonly EXPERIMENT_STARTED: "experiment_started";
    readonly EXPERIMENT_COMPLETED: "experiment_completed";
};
export declare const ML_MODEL_TYPES: {
    readonly USER_PERSONA_CLASSIFIER: "user_persona_classifier";
    readonly ENGAGEMENT_PREDICTOR: "engagement_predictor";
    readonly SUCCESS_PREDICTOR: "success_predictor";
    readonly STRUGGLE_DETECTOR: "struggle_detector";
    readonly CONTENT_RECOMMENDER: "content_recommender";
    readonly PATH_OPTIMIZER: "path_optimizer";
    readonly INTERVENTION_SELECTOR: "intervention_selector";
    readonly PROFICIENCY_ASSESSOR: "proficiency_assessor";
};
export declare const PERFORMANCE_THRESHOLDS: {
    readonly EVENT_PROCESSING: 100;
    readonly ML_PREDICTION: 2000;
    readonly INTERVENTION_TRIGGER: 3000;
    readonly CONTENT_ADAPTATION: 1000;
    readonly LOW_ENGAGEMENT: 40;
    readonly MEDIUM_ENGAGEMENT: 60;
    readonly HIGH_ENGAGEMENT: 80;
    readonly LOW_SUCCESS_PROBABILITY: 30;
    readonly MEDIUM_SUCCESS_PROBABILITY: 70;
    readonly HIGH_SUCCESS_PROBABILITY: 85;
    readonly STRUGGLE_TIME_THRESHOLD: 15000;
    readonly ERROR_FREQUENCY_THRESHOLD: 3;
    readonly HESITATION_THRESHOLD: 5000;
    readonly MAX_MEMORY_USAGE: 0.8;
    readonly MAX_CPU_USAGE: 0.7;
    readonly MIN_CACHE_HIT_RATE: 0.85;
    readonly MAX_ERROR_RATE: 0.01;
};
export declare const FEATURE_FLAGS: {
    readonly SMART_ONBOARDING_ENABLED: "smart_onboarding_enabled";
    readonly BEHAVIORAL_ANALYTICS: "behavioral_analytics_enabled";
    readonly ML_PERSONALIZATION: "ml_personalization_enabled";
    readonly REAL_TIME_ADAPTATION: "real_time_adaptation_enabled";
    readonly PREDICTIVE_INTERVENTIONS: "predictive_interventions_enabled";
    readonly DYNAMIC_CONTENT_ADAPTATION: "dynamic_content_adaptation_enabled";
    readonly ADVANCED_ANALYTICS: "advanced_analytics_enabled";
    readonly A_B_TESTING: "ab_testing_enabled";
    readonly FEDERATED_LEARNING: "federated_learning_enabled";
    readonly ADVANCED_NLP: "advanced_nlp_enabled";
    readonly COMPUTER_VISION: "computer_vision_enabled";
    readonly VOICE_INTERACTION: "voice_interaction_enabled";
};
export declare const API_ENDPOINTS: {
    readonly INITIALIZE_JOURNEY: "/api/smart-onboarding/journey/initialize";
    readonly UPDATE_PROGRESS: "/api/smart-onboarding/journey/progress";
    readonly GET_NEXT_STEP: "/api/smart-onboarding/journey/next-step";
    readonly COMPLETE_JOURNEY: "/api/smart-onboarding/journey/complete";
    readonly TRACK_INTERACTION: "/api/smart-onboarding/analytics/track";
    readonly GET_ENGAGEMENT: "/api/smart-onboarding/analytics/engagement";
    readonly GET_INSIGHTS: "/api/smart-onboarding/analytics/insights";
    readonly GET_PERSONA: "/api/smart-onboarding/ml/persona";
    readonly GET_PREDICTIONS: "/api/smart-onboarding/ml/predictions";
    readonly GET_RECOMMENDATIONS: "/api/smart-onboarding/ml/recommendations";
    readonly UPDATE_MODEL: "/api/smart-onboarding/ml/model/update";
    readonly TRIGGER_INTERVENTION: "/api/smart-onboarding/intervention/trigger";
    readonly GET_HELP: "/api/smart-onboarding/intervention/help";
    readonly ESCALATE_ISSUE: "/api/smart-onboarding/intervention/escalate";
    readonly ADAPT_CONTENT: "/api/smart-onboarding/content/adapt";
    readonly GET_VARIATIONS: "/api/smart-onboarding/content/variations";
    readonly OPTIMIZE_PATH: "/api/smart-onboarding/content/optimize-path";
    readonly GET_DASHBOARD: "/api/smart-onboarding/admin/dashboard";
    readonly GET_METRICS: "/api/smart-onboarding/admin/metrics";
    readonly MANAGE_EXPERIMENTS: "/api/smart-onboarding/admin/experiments";
    readonly SYSTEM_HEALTH: "/api/smart-onboarding/admin/health";
};
export declare const ERROR_CODES: {
    readonly INVALID_REQUEST: "SMART_ONBOARDING_INVALID_REQUEST";
    readonly UNAUTHORIZED: "SMART_ONBOARDING_UNAUTHORIZED";
    readonly FORBIDDEN: "SMART_ONBOARDING_FORBIDDEN";
    readonly NOT_FOUND: "SMART_ONBOARDING_NOT_FOUND";
    readonly JOURNEY_NOT_FOUND: "SMART_ONBOARDING_JOURNEY_NOT_FOUND";
    readonly JOURNEY_ALREADY_EXISTS: "SMART_ONBOARDING_JOURNEY_ALREADY_EXISTS";
    readonly JOURNEY_COMPLETED: "SMART_ONBOARDING_JOURNEY_COMPLETED";
    readonly INVALID_STEP: "SMART_ONBOARDING_INVALID_STEP";
    readonly MODEL_NOT_AVAILABLE: "SMART_ONBOARDING_MODEL_NOT_AVAILABLE";
    readonly PREDICTION_FAILED: "SMART_ONBOARDING_PREDICTION_FAILED";
    readonly MODEL_TRAINING_FAILED: "SMART_ONBOARDING_MODEL_TRAINING_FAILED";
    readonly INSUFFICIENT_DATA: "SMART_ONBOARDING_INSUFFICIENT_DATA";
    readonly TRACKING_FAILED: "SMART_ONBOARDING_TRACKING_FAILED";
    readonly ANALYTICS_UNAVAILABLE: "SMART_ONBOARDING_ANALYTICS_UNAVAILABLE";
    readonly INVALID_METRICS: "SMART_ONBOARDING_INVALID_METRICS";
    readonly INTERVENTION_FAILED: "SMART_ONBOARDING_INTERVENTION_FAILED";
    readonly HELP_UNAVAILABLE: "SMART_ONBOARDING_HELP_UNAVAILABLE";
    readonly ESCALATION_FAILED: "SMART_ONBOARDING_ESCALATION_FAILED";
    readonly CONTENT_NOT_FOUND: "SMART_ONBOARDING_CONTENT_NOT_FOUND";
    readonly ADAPTATION_FAILED: "SMART_ONBOARDING_ADAPTATION_FAILED";
    readonly OPTIMIZATION_FAILED: "SMART_ONBOARDING_OPTIMIZATION_FAILED";
    readonly SERVICE_UNAVAILABLE: "SMART_ONBOARDING_SERVICE_UNAVAILABLE";
    readonly RATE_LIMIT_EXCEEDED: "SMART_ONBOARDING_RATE_LIMIT_EXCEEDED";
    readonly INTERNAL_ERROR: "SMART_ONBOARDING_INTERNAL_ERROR";
    readonly EXTERNAL_SERVICE_ERROR: "SMART_ONBOARDING_EXTERNAL_SERVICE_ERROR";
};
export declare const RATE_LIMITS: {
    readonly TRACK_INTERACTION: 1000;
    readonly GET_RECOMMENDATIONS: 60;
    readonly TRIGGER_INTERVENTION: 10;
    readonly UPDATE_PROGRESS: 100;
    readonly GENERAL_API: 1000;
    readonly ML_ENDPOINTS: 100;
    readonly ADMIN_ENDPOINTS: 60;
    readonly CONCURRENT_JOURNEYS: 10000;
    readonly CONCURRENT_ML_PREDICTIONS: 500;
    readonly CONCURRENT_INTERVENTIONS: 1000;
};
export declare const DATA_RETENTION: {
    readonly BEHAVIOR_EVENTS: 90;
    readonly INTERACTION_DATA: 30;
    readonly ENGAGEMENT_METRICS: 365;
    readonly TRAINING_DATA: 730;
    readonly MODEL_PREDICTIONS: 180;
    readonly EXPERIMENT_DATA: 365;
    readonly COMPLETED_JOURNEYS: 1095;
    readonly ABANDONED_JOURNEYS: 365;
    readonly USER_PROFILES: -1;
    readonly SYSTEM_METRICS: 90;
    readonly ERROR_LOGS: 30;
    readonly PERFORMANCE_LOGS: 7;
};
export declare const MONITORING_ALERTS: {
    readonly HIGH_RESPONSE_TIME: {
        readonly threshold: 5000;
        readonly severity: "warning";
    };
    readonly LOW_SUCCESS_RATE: {
        readonly threshold: 0.8;
        readonly severity: "critical";
    };
    readonly HIGH_ERROR_RATE: {
        readonly threshold: 0.05;
        readonly severity: "error";
    };
    readonly LOW_ENGAGEMENT: {
        readonly threshold: 0.4;
        readonly severity: "warning";
    };
    readonly HIGH_ABANDONMENT: {
        readonly threshold: 0.3;
        readonly severity: "critical";
    };
    readonly FREQUENT_INTERVENTIONS: {
        readonly threshold: 5;
        readonly severity: "warning";
    };
    readonly HIGH_MEMORY_USAGE: {
        readonly threshold: 0.9;
        readonly severity: "critical";
    };
    readonly HIGH_CPU_USAGE: {
        readonly threshold: 0.8;
        readonly severity: "warning";
    };
    readonly LOW_CACHE_HIT_RATE: {
        readonly threshold: 0.7;
        readonly severity: "warning";
    };
};
import { getPool } from '../../db';
export declare const smartOnboardingDb: {
    query: (text: string, params?: any[]) => Promise<import("pg").QueryResult<any>>;
    getPool: typeof getPool;
    tables: {
        readonly USER_PROFILES: "smart_onboarding_user_profiles";
        readonly ONBOARDING_JOURNEYS: "smart_onboarding_journeys";
        readonly ONBOARDING_STEPS: "smart_onboarding_steps";
        readonly LEARNING_PATHS: "smart_onboarding_learning_paths";
        readonly BEHAVIOR_EVENTS: "smart_onboarding_behavior_events";
        readonly INTERACTION_DATA: "smart_onboarding_interaction_data";
        readonly ENGAGEMENT_METRICS: "smart_onboarding_engagement_metrics";
        readonly STRUGGLE_INDICATORS: "smart_onboarding_struggle_indicators";
        readonly USER_PERSONAS: "smart_onboarding_user_personas";
        readonly PREDICTION_MODELS: "smart_onboarding_prediction_models";
        readonly MODEL_TRAINING_DATA: "smart_onboarding_model_training_data";
        readonly SUCCESS_PREDICTIONS: "smart_onboarding_success_predictions";
        readonly INTERVENTIONS: "smart_onboarding_interventions";
        readonly INTERVENTION_OUTCOMES: "smart_onboarding_intervention_outcomes";
        readonly HELP_CONTENT: "smart_onboarding_help_content";
        readonly ESCALATION_TICKETS: "smart_onboarding_escalation_tickets";
        readonly CONTENT_VARIATIONS: "smart_onboarding_content_variations";
        readonly PERSONALIZED_CONTENT: "smart_onboarding_personalized_content";
        readonly CONTENT_RECOMMENDATIONS: "smart_onboarding_content_recommendations";
        readonly ADAPTATION_HISTORY: "smart_onboarding_adaptation_history";
        readonly BEHAVIORAL_INSIGHTS: "smart_onboarding_behavioral_insights";
        readonly PATH_PERFORMANCE: "smart_onboarding_path_performance";
        readonly EXPERIMENT_RESULTS: "smart_onboarding_experiment_results";
        readonly SYSTEM_METRICS: "smart_onboarding_system_metrics";
    };
    cacheKeys: {
        readonly USER_PROFILE: (userId: string) => string;
        readonly USER_JOURNEY: (userId: string) => string;
        readonly USER_PERSONA: (userId: string) => string;
        readonly ENGAGEMENT_SCORE: (userId: string) => string;
        readonly LEARNING_PATH: (pathId: string) => string;
        readonly STEP_CONTENT: (stepId: string) => string;
        readonly CONTENT_RECOMMENDATIONS: (userId: string, stepId: string) => string;
        readonly MODEL_PREDICTIONS: (userId: string, modelType: string) => string;
        readonly SUCCESS_PREDICTION: (userId: string) => string;
        readonly SYSTEM_METRICS: "smart_onboarding:system_metrics";
        readonly ACTIVE_EXPERIMENTS: "smart_onboarding:active_experiments";
        readonly MODEL_PERFORMANCE: (modelId: string) => string;
    };
    cacheTtl: {
        readonly ENGAGEMENT_SCORE: 60;
        readonly BEHAVIOR_EVENTS: 300;
        readonly REAL_TIME_METRICS: 30;
        readonly USER_JOURNEY: 1800;
        readonly CONTENT_RECOMMENDATIONS: 900;
        readonly INTERVENTION_PLANS: 600;
        readonly USER_PROFILE: 3600;
        readonly USER_PERSONA: 7200;
        readonly LEARNING_PATH: 14400;
        readonly STEP_CONTENT: 21600;
        readonly MODEL_PREDICTIONS: 1800;
        readonly SUCCESS_PREDICTION: 3600;
        readonly MODEL_PERFORMANCE: 86400;
        readonly SYSTEM_METRICS: 300;
        readonly ACTIVE_EXPERIMENTS: 3600;
    };
};
