/**
 * Load Shedding System Initialization
 * Auto-generated by setup-load-shedding.js
 */

import { admissionController } from '@/lib/load-shedding/admissionController';
import { apiThrottling, databaseThrottling, cacheThrottling } from '@/lib/load-shedding/clientThrottling';
import { loadSheddingMiddleware } from '@/lib/load-shedding/middleware';

let loadSheddingInitialized = false;

export async function initializeLoadShedding() {
  if (loadSheddingInitialized) {
    console.log('Load shedding already initialized');
    return;
  }

  try {
    console.log('🚀 Initializing load shedding system...');

    // Load configuration
    const config = await loadConfiguration();
    
    // Update admission controller config
    if (config.admissionControl) {
      admissionController.updateConfig(config.admissionControl);
      console.log('✅ Admission controller configured');
    }

    // Update client throttling configs
    if (config.clientThrottling) {
      if (config.clientThrottling.api) {
        apiThrottling.updateConfig(config.clientThrottling.api);
      }
      if (config.clientThrottling.database) {
        databaseThrottling.updateConfig(config.clientThrottling.database);
      }
      if (config.clientThrottling.cache) {
        cacheThrottling.updateConfig(config.clientThrottling.cache);
      }
      console.log('✅ Client throttling configured');
    }

    // Update middleware config
    if (config.middleware) {
      loadSheddingMiddleware.updateConfig(config.middleware);
      console.log('✅ Load shedding middleware configured');
    }

    loadSheddingInitialized = true;
    console.log('🎯 Load shedding system initialized successfully');

    // Start monitoring
    startLoadSheddingMonitoring();
  } catch (error) {
    console.error('❌ Load shedding initialization failed:', error);
    throw error;
  }
}

async function loadConfiguration() {
  try {
    const fs = await import('fs/promises');
    const configData = await fs.readFile('load-shedding.config.json', 'utf8');
    return JSON.parse(configData);
  } catch (error) {
    console.warn('Could not load load-shedding.config.json, using defaults');
    return {};
  }
}

function startLoadSheddingMonitoring() {
  // Monitor system resources every 30 seconds
  setInterval(async () => {
    try {
      const status = admissionController.getStatus();
      
      // Log warnings for high resource usage
      if (status.shedLevel >= 2) {
        console.warn(`⚠️  Load shedding active (level ${status.shedLevel})`);
      }
      
      // Log throttling status
      const throttlingMetrics = {
        api: apiThrottling.getMetrics(),
        database: databaseThrottling.getMetrics(),
        cache: cacheThrottling.getMetrics()
      };
      
      const activeThrottling = Object.entries(throttlingMetrics)
        .filter(([_, metrics]) => metrics.isThrottling)
        .map(([service, _]) => service);
      
      if (activeThrottling.length > 0) {
        console.warn(`🔄 Client throttling active: ${activeThrottling.join(', ')}`);
      }
    } catch (error) {
      console.error('Load shedding monitoring error:', error);
    }
  }, 30000);
}

// Auto-initialize in production
if (process.env.NODE_ENV === 'production') {
  initializeLoadShedding().catch(console.error);
}

// Export for manual initialization
export { admissionController, apiThrottling, databaseThrottling, cacheThrottling, loadSheddingMiddleware };
