import { UserPersona, OnboardingJourney } from '../types';
type MLPrediction = any;
export declare class CacheOptimizer {
    private cacheManager;
    private redisClient;
    private cacheHitRates;
    private cacheStrategies;
    constructor();
    initialize(): Promise<void>;
    private setWithTTL;
    private get;
    private cleanup;
    private initializeCacheStrategies;
    cacheMLPrediction(userId: string, predictionType: string, inputHash: string, prediction: MLPrediction): Promise<void>;
    getCachedMLPrediction(userId: string, predictionType: string, inputHash: string): Promise<MLPrediction | null>;
    cacheUserPersona(userId: string, persona: UserPersona): Promise<void>;
    getCachedUserPersona(userId: string): Promise<UserPersona | null>;
    cacheOnboardingJourney(userId: string, journey: OnboardingJourney): Promise<void>;
    getCachedOnboardingJourney(userId: string): Promise<OnboardingJourney | null>;
    cacheBehavioralAnalytics(userId: string, timeWindow: string, analytics: any): Promise<void>;
    getCachedBehavioralAnalytics(userId: string, timeWindow: string): Promise<any | null>;
    cacheInterventionContent(contentType: string, contextHash: string, content: any): Promise<void>;
    getCachedInterventionContent(contentType: string, contextHash: string): Promise<any | null>;
    warmupCache(): Promise<void>;
    private warmupMLPredictions;
    private warmupInterventionContent;
    private warmupUserPersonas;
    private prefetchRelatedPersonaData;
    private prefetchMLPrediction;
    private getPredictedMLRequests;
    optimizeCachePerformance(): Promise<void>;
    private analyzeCacheHitRates;
    private adjustCacheStrategy;
    private optimizeCacheStrategies;
    private cleanupCache;
    private setupCacheWarmup;
    private compressData;
    private decompressData;
    private updateCacheMetrics;
    getCacheStatistics(): Map<string, any>;
    generateCacheReport(): Promise<string>;
}
export {};
