AWSTemplateFormatVersion: '2010-09-09'
Description: 'Huntaze Beta CloudFront Distribution with S3 and Vercel Origins'

Parameters:
  S3BucketName:
    Type: String
    Default: huntaze-beta-assets
    Description: Name of the S3 bucket for static assets
  
  VercelDomain:
    Type: String
    Default: huntaze.vercel.app
    Description: Vercel domain for dynamic content
  
  CustomDomain:
    Type: String
    Default: beta.huntaze.com
    Description: Custom domain for CloudFront distribution
  
  ACMCertificateArn:
    Type: String
    Description: ARN of ACM certificate for custom domain (must be in us-east-1)
    Default: ''
  
  SecurityHeadersLambdaArn:
    Type: String
    Description: ARN of Lambda@Edge function for security headers (with version)
    Default: ''
  
  ImageOptimizationLambdaArn:
    Type: String
    Description: ARN of Lambda@Edge function for image optimization (with version)
    Default: ''
  
  Environment:
    Type: String
    Default: beta
    AllowedValues:
      - beta
      - production
    Description: Environment name

Resources:
  # CloudFront Origin Access Identity for S3
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${S3BucketName}'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub 'Huntaze ${Environment} Distribution'
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations
        
        # Custom Domain Configuration
        Aliases: !If
          - HasCustomDomain
          - [!Ref CustomDomain]
          - !Ref AWS::NoValue
        
        ViewerCertificate: !If
          - HasACMCertificate
          - AcmCertificateArn: !Ref ACMCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        
        # Origins
        Origins:
          # S3 Origin for Static Assets
          - Id: S3-Static-Assets
            DomainName: !Sub '${S3BucketName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
          
          # Vercel Origin for Dynamic Content
          - Id: Vercel-App
            DomainName: !Ref VercelDomain
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
        
        # Default Cache Behavior (Dynamic Content - Vercel)
        DefaultCacheBehavior:
          TargetOriginId: Vercel-App
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          
          # Cache Policy for Dynamic Content
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled managed policy
          
          # Origin Request Policy
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3  # AllViewer managed policy
          
          # Response Headers Policy (Security Headers)
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          
          # Lambda@Edge Functions
          LambdaFunctionAssociations: !If
            - HasSecurityHeadersLambda
            - - EventType: viewer-response
                LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
            - !Ref AWS::NoValue
        
        # Cache Behaviors for Static Assets
        CacheBehaviors:
          # Next.js Static Assets (Immutable - 1 year cache)
          - PathPattern: '/_next/static/*'
            TargetOriginId: S3-Static-Assets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            CachePolicyId: !Ref ImmutableCachePolicy
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            LambdaFunctionAssociations: !If
              - HasSecurityHeadersLambda
              - - EventType: viewer-response
                  LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
              - !Ref AWS::NoValue
          
          # Images (1 day cache with revalidation)
          - PathPattern: '/images/*'
            TargetOriginId: S3-Static-Assets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            CachePolicyId: !Ref ImageCachePolicy
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            LambdaFunctionAssociations: !If
              - HasBothLambdas
              - - EventType: origin-request
                  LambdaFunctionARN: !Ref ImageOptimizationLambdaArn
                - EventType: viewer-response
                  LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
              - !If
                - HasImageOptimizationLambda
                - - EventType: origin-request
                    LambdaFunctionARN: !Ref ImageOptimizationLambdaArn
                - !If
                  - HasSecurityHeadersLambda
                  - - EventType: viewer-response
                      LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
                  - !Ref AWS::NoValue
          
          # Public Assets
          - PathPattern: '/public/*'
            TargetOriginId: S3-Static-Assets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            CachePolicyId: !Ref ImageCachePolicy
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
            LambdaFunctionAssociations: !If
              - HasBothLambdas
              - - EventType: origin-request
                  LambdaFunctionARN: !Ref ImageOptimizationLambdaArn
                - EventType: viewer-response
                  LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
              - !If
                - HasImageOptimizationLambda
                - - EventType: origin-request
                    LambdaFunctionARN: !Ref ImageOptimizationLambdaArn
                - !If
                  - HasSecurityHeadersLambda
                  - - EventType: viewer-response
                      LambdaFunctionARN: !Ref SecurityHeadersLambdaArn
                  - !Ref AWS::NoValue
        
        # Custom Error Responses
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 500
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ErrorCachingMinTTL: 0
        
        # Logging Configuration
        Logging:
          Bucket: !GetAtt LoggingBucket.DomainName
          Prefix: !Sub 'cloudfront/${Environment}/'
          IncludeCookies: false
      
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Huntaze
        - Key: ManagedBy
          Value: CloudFormation

  # Cache Policy for Immutable Assets (1 year)
  ImmutableCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub 'Huntaze-${Environment}-Immutable-Cache'
        Comment: 'Cache policy for immutable static assets (1 year)'
        DefaultTTL: 31536000  # 1 year
        MaxTTL: 31536000      # 1 year
        MinTTL: 31536000      # 1 year
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          QueryStringsConfig:
            QueryStringBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none

  # Cache Policy for Images (1 day with revalidation)
  ImageCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub 'Huntaze-${Environment}-Image-Cache'
        Comment: 'Cache policy for images (1 day)'
        DefaultTTL: 86400     # 1 day
        MaxTTL: 31536000      # 1 year
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          QueryStringsConfig:
            QueryStringBehavior: none
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Accept
              - CloudFront-Is-Desktop-Viewer
              - CloudFront-Is-Mobile-Viewer
              - CloudFront-Is-Tablet-Viewer
          CookiesConfig:
            CookieBehavior: none

  # Response Headers Policy (Security Headers)
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub 'Huntaze-${Environment}-Security-Headers'
        Comment: 'Security headers for Huntaze application'
        
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          
          ContentTypeOptions:
            Override: true
          
          FrameOptions:
            FrameOption: DENY
            Override: true
          
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: true
          
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true
          
          ContentSecurityPolicy:
            ContentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://vercel.live; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://*.huntaze.com https://vercel.live; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
            Override: true
        
        CustomHeadersConfig:
          Items:
            - Header: Permissions-Policy
              Value: 'geolocation=(), microphone=(), camera=()'
              Override: true
            - Header: X-Content-Type-Options
              Value: nosniff
              Override: true

  # S3 Bucket for CloudFront Logs
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketName}-logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 90
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: Huntaze
        - Key: Purpose
          Value: CloudFront Logs

  # CloudWatch Alarms
  HighErrorRateAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Huntaze-${Environment}-CloudFront-High-Error-Rate'
      AlarmDescription: 'Alert when CloudFront 5XX error rate is high'
      MetricName: 5xxErrorRate
      Namespace: AWS/CloudFront
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1.0  # 1% error rate
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
      TreatMissingData: notBreaching

  LowCacheHitRatioAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Huntaze-${Environment}-CloudFront-Low-Cache-Hit-Ratio'
      AlarmDescription: 'Alert when CloudFront cache hit ratio is low'
      MetricName: CacheHitRate
      Namespace: AWS/CloudFront
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80.0  # 80% cache hit rate
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
      TreatMissingData: notBreaching

  HighOriginLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Huntaze-${Environment}-CloudFront-High-Origin-Latency'
      AlarmDescription: 'Alert when origin latency is high'
      MetricName: OriginLatency
      Namespace: AWS/CloudFront
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1000  # 1 second
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DistributionId
          Value: !Ref CloudFrontDistribution
      TreatMissingData: notBreaching

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref CustomDomain, '']]
  HasACMCertificate: !Not [!Equals [!Ref ACMCertificateArn, '']]
  HasSecurityHeadersLambda: !Not [!Equals [!Ref SecurityHeadersLambdaArn, '']]
  HasImageOptimizationLambda: !Not [!Equals [!Ref ImageOptimizationLambdaArn, '']]
  HasBothLambdas: !And
    - !Not [!Equals [!Ref SecurityHeadersLambdaArn, '']]
    - !Not [!Equals [!Ref ImageOptimizationLambdaArn, '']]

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  
  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  
  CloudFrontOAIId:
    Description: CloudFront Origin Access Identity ID
    Value: !Ref CloudFrontOAI
    Export:
      Name: !Sub '${AWS::StackName}-OAI-Id'
  
  CloudFrontOAICanonicalUserId:
    Description: CloudFront OAI Canonical User ID (for S3 bucket policy)
    Value: !GetAtt CloudFrontOAI.S3CanonicalUserId
    Export:
      Name: !Sub '${AWS::StackName}-OAI-CanonicalUserId'
  
  LoggingBucketName:
    Description: S3 bucket for CloudFront logs
    Value: !Ref LoggingBucket
    Export:
      Name: !Sub '${AWS::StackName}-LoggingBucket'
  
  SecurityHeadersPolicyId:
    Description: Response Headers Policy ID for security headers
    Value: !Ref SecurityHeadersPolicy
    Export:
      Name: !Sub '${AWS::StackName}-SecurityHeadersPolicy'
