AWSTemplateFormatVersion: '2010-09-09'
Description: 'Huntaze Authentication - Simplified Cognito Setup'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: 'Deployment environment'

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'huntaze-${Environment}-users'
      
      # Email as username
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      
      # Password policy
      Policies:
        PasswordPolicy:
          MinimumLength: 14
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      
      # Email configuration
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      
      EmailVerificationMessage: |
        Your Huntaze verification code is {####}
      EmailVerificationSubject: 'Huntaze - Verify your email'
      
      # Schema
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: false
      
      # MFA
      MfaConfiguration: 'OFF'
      
      # Account recovery
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'huntaze-${Environment}-web'
      UserPoolId: !Ref UserPool
      
      # Auth settings
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      
      # Token validity
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      
      # Security
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      
      # Attributes
      ReadAttributes:
        - email
        - email_verified
        - name
      WriteAttributes:
        - email
        - name

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'huntaze-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Description: 'Cognito User Pool ID'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'
  
  UserPoolClientId:
    Value: !Ref UserPoolClient
    Description: 'Cognito User Pool Client ID'
    Export:
      Name: !Sub '${AWS::StackName}-ClientId'
  
  CognitoDomain:
    Value: !Sub 'https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Description: 'Cognito Hosted UI Domain'