groups:
  - name: social.recording
    interval: 30s
    rules:
      - record: social:publish_p95_seconds
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, platform) (rate(social_publish_time_seconds_bucket[5m]))
          )
      - record: social:tiktok:webhooks_15m
        expr: increase(social_tiktok_webhook_events_total[15m])
      - record: social:tiktok:publishes_15m
        expr: increase(social_tiktok_publish_requests_total[15m])
      - record: social:reddit:429_ratio_5m
        expr: |
          sum(rate(social_rate_limit_hits_total{platform="reddit"}[5m]))
          /
          clamp_min(sum(rate(social_publish_time_seconds_count{platform="reddit"}[5m])), 1)

  - name: social.alerts.tiktok
    interval: 30s
    rules:
      - alert: TikTokPublishLatencyP95High
        expr: social:publish_p95_seconds{platform="tiktok"} > 90
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "TikTok publish p95 > 120s for 10m"
          runbook: "Check status poller/webhooks; see /api/metrics and EMF logs."

      - alert: TikTokWebhookSilence
        expr: increase(social_tiktok_publish_requests_total[10m]) > 0
          and increase(social_tiktok_webhook_events_total[10m]) == 0
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "No TikTok terminal webhooks in 15m despite publishes"
          runbook: "Verify webhook signature/ingress; poller continues as fallback."

  - name: social.alerts.slo
    interval: 1m
    rules:
      - record: social:tiktok:error_ratio5m
        expr: |
          sum(rate(social_tiktok_publish_requests_total{result=~"error|failed"}[5m]))
          /
          clamp_min(sum(rate(social_tiktok_publish_requests_total[5m])), 1)
      - record: social:tiktok:error_ratio1h
        expr: |
          sum(rate(social_tiktok_publish_requests_total{result=~"error|failed"}[1h]))
          /
          clamp_min(sum(rate(social_tiktok_publish_requests_total[1h])), 1)

      - alert: TikTokSLOBudgetBurnFast
        expr: (social:tiktok:error_ratio5m > (14.4 * 0.001))
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "TikTok SLO fast burn >14.4x (5m window)"

      - alert: TikTokSLOBudgetBurnSlow
        expr: (social:tiktok:error_ratio1h > (6 * 0.001))
        for: 1h
        labels:
          severity: ticket
        annotations:
          summary: "TikTok SLO slow burn >6x (1h window)"

  - name: social.alerts.reddit
    interval: 1m
    rules:
      - alert: RedditRateLimitBudgetExceeded
        expr: social:reddit:429_ratio_5m > 0.02
        for: 10m
        labels:
          severity: ticket
        annotations:
          summary: "Reddit 429s >2% of publishes (5m)"
          hint: "Consider lowering canary or spreading across client IDs."

  - name: social.alerts.scheduler
    interval: 1m
    rules:
      - alert: InsightsSchedulerLagHigh
        expr: insights_scheduler_lag_seconds > 300
        for: 10m
        labels:
          severity: page
        annotations:
          summary: "Insights scheduler lag > 300s for 10m"
          runbook: "Check scheduler workers, quotas, and API latency; see /api/metrics and EMF logs."
