#!/bin/bash

# Azure AI Infrastructure Deployment Script
# This script deploys the Azure OpenAI Service and related resources

set -e

echo "🚀 Azure AI Infrastructure Deployment"
echo "======================================"

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo "❌ Azure CLI is not installed. Please install it first:"
    echo "   https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform is not installed. Please install it first:"
    echo "   https://www.terraform.io/downloads"
    exit 1
fi

# Check if logged in to Azure
echo "🔐 Checking Azure authentication..."
if ! az account show &> /dev/null; then
    echo "❌ Not logged in to Azure. Please run: az login"
    exit 1
fi

# Get current subscription
SUBSCRIPTION=$(az account show --query name -o tsv)
echo "✅ Logged in to Azure subscription: $SUBSCRIPTION"

# Prompt for environment
read -p "Enter environment (dev/staging/production) [production]: " ENVIRONMENT
ENVIRONMENT=${ENVIRONMENT:-production}

echo ""
echo "📋 Deployment Configuration:"
echo "   Environment: $ENVIRONMENT"
echo "   Primary Region: eastus (US East)"
echo ""

read -p "Continue with deployment? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "❌ Deployment cancelled"
    exit 0
fi

# Initialize Terraform
echo ""
echo "🔧 Initializing Terraform..."
terraform init

# Validate configuration
echo ""
echo "✅ Validating Terraform configuration..."
terraform validate

# Plan deployment
echo ""
echo "📝 Planning deployment..."
terraform plan -var="environment=$ENVIRONMENT" -out=tfplan

# Apply deployment
echo ""
read -p "Apply this plan? (yes/no): " APPLY_CONFIRM
if [ "$APPLY_CONFIRM" != "yes" ]; then
    echo "❌ Deployment cancelled"
    exit 0
fi

echo ""
echo "🚀 Applying Terraform configuration..."
terraform apply tfplan

# Get outputs
echo ""
echo "📊 Deployment Outputs:"
echo "====================="
terraform output

# Save outputs to .env file
echo ""
echo "💾 Saving configuration to .env.azure..."
OPENAI_ENDPOINT=$(terraform output -raw openai_primary_endpoint)
SEARCH_ENDPOINT=$(terraform output -raw cognitive_search_endpoint)
INSIGHTS_KEY=$(terraform output -raw application_insights_instrumentation_key)
KV_URI=$(terraform output -raw key_vault_uri)

cat > ../../../.env.azure << EOF
# Azure OpenAI Configuration (Generated by Terraform)
AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY=\$(az keyvault secret show --vault-name huntaze-ai-$ENVIRONMENT-kv --name azure-openai-primary-key --query value -o tsv)
AZURE_USE_MANAGED_IDENTITY=false

# Azure OpenAI Deployments
AZURE_OPENAI_DEPLOYMENT_PREMIUM=gpt-4-turbo-prod
AZURE_OPENAI_DEPLOYMENT_STANDARD=gpt-4-standard-prod
AZURE_OPENAI_DEPLOYMENT_ECONOMY=gpt-35-turbo-prod
AZURE_OPENAI_DEPLOYMENT_VISION=gpt-4-vision-prod
AZURE_OPENAI_DEPLOYMENT_EMBEDDING=text-embedding-ada-002-prod

# Azure Cognitive Search
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_API_KEY=\$(az search admin-key show --resource-group huntaze-ai-$ENVIRONMENT-rg --service-name huntaze-ai-$ENVIRONMENT-search --query primaryKey -o tsv)
AZURE_SEARCH_INDEX_NAME=huntaze-memory-index

# Azure Application Insights
AZURE_APPLICATION_INSIGHTS_INSTRUMENTATION_KEY=$INSIGHTS_KEY
AZURE_APPLICATION_INSIGHTS_CONNECTION_STRING=\$(terraform output -raw application_insights_connection_string)

# Azure Key Vault
AZURE_KEY_VAULT_URI=$KV_URI

# Azure Regions
AZURE_PRIMARY_REGION=westeurope
AZURE_SECONDARY_REGION=northeurope

# Feature Flags
ENABLE_AZURE_AI=false
AZURE_AI_ROLLOUT_PERCENTAGE=0
EOF

echo "✅ Configuration saved to .env.azure"
echo ""
echo "🎉 Deployment Complete!"
echo ""
echo "📝 Next Steps:"
echo "   1. Review the .env.azure file"
echo "   2. Retrieve API keys from Key Vault:"
echo "      az keyvault secret show --vault-name huntaze-ai-$ENVIRONMENT-kv --name azure-openai-primary-key"
echo "   3. Update your application configuration"
echo "   4. Test the Azure OpenAI endpoints"
echo ""
echo "📚 Documentation:"
echo "   - Azure OpenAI: https://learn.microsoft.com/en-us/azure/ai-services/openai/"
echo "   - Cognitive Search: https://learn.microsoft.com/en-us/azure/search/"
echo ""
