/**
 * Recovery System Initialization
 * Auto-generated by setup-recovery.js
 */

import { setupDefaultHealthChecks } from '@/lib/recovery/healthChecker';
import { setupDefaultDegradationRules } from '@/lib/recovery/gracefulDegradation';
import { setupDefaultHealingActions } from '@/lib/recovery/autoHealing';

let recoveryInitialized = false;

export async function initializeRecoverySystem() {
  if (recoveryInitialized) {
    console.log('Recovery system already initialized');
    return;
  }

  try {
    console.log('🔧 Initializing recovery system...');

    // Setup health checks
    setupDefaultHealthChecks();
    console.log('✅ Health checks configured');

    // Setup degradation rules
    setupDefaultDegradationRules();
    console.log('✅ Graceful degradation rules configured');

    // Setup auto-healing actions
    setupDefaultHealingActions();
    console.log('✅ Auto-healing actions configured');

    recoveryInitialized = true;
    console.log('🚀 Recovery system initialized successfully');

    // Start periodic evaluations
    startPeriodicEvaluations();
  } catch (error) {
    console.error('❌ Recovery system initialization failed:', error);
    throw error;
  }
}

function startPeriodicEvaluations() {
  // Health check evaluation every 30 seconds
  setInterval(async () => {
    try {
      const { healthChecker } = await import('@/lib/recovery/healthChecker');
      await healthChecker.runAllChecks();
    } catch (error) {
      console.error('Health check evaluation failed:', error);
    }
  }, 30000);

  // Degradation rule evaluation every minute
  setInterval(async () => {
    try {
      const { degradationManager } = await import('@/lib/recovery/gracefulDegradation');
      await degradationManager.evaluateRules();
    } catch (error) {
      console.error('Degradation rule evaluation failed:', error);
    }
  }, 60000);
}

// Auto-initialize in production
if (process.env.NODE_ENV === 'production') {
  initializeRecoverySystem().catch(console.error);
}
