/**
 * Safe Deployments Initialization
 * Auto-generated by setup-safe-deployments.js
 */

import { canaryController } from '@/lib/deployments/canaryController';
import { blueGreenController } from '@/lib/deployments/blueGreenController';
import { errorBudgetGate, setupDefaultErrorBudgetGates } from '@/lib/deployments/errorBudgetGate';

let deploymentsInitialized = false;

export async function initializeSafeDeployments() {
  if (deploymentsInitialized) {
    console.log('Safe deployments already initialized');
    return;
  }

  try {
    console.log('🚀 Initializing safe deployments system...');

    // Setup error budget gates
    setupDefaultErrorBudgetGates();
    console.log('✅ Error budget gates configured');

    // Start continuous monitoring
    errorBudgetGate.startContinuousMonitoring();
    console.log('✅ Error budget monitoring started');

    deploymentsInitialized = true;
    console.log('🎯 Safe deployments system initialized successfully');

    // Start periodic cleanup
    startPeriodicCleanup();
  } catch (error) {
    console.error('❌ Safe deployments initialization failed:', error);
    throw error;
  }
}

function startPeriodicCleanup() {
  // Clean up old deployment records every hour
  setInterval(() => {
    try {
      cleanupOldDeployments();
    } catch (error) {
      console.error('Deployment cleanup failed:', error);
    }
  }, 3600000); // 1 hour
}

function cleanupOldDeployments() {
  const cutoffTime = Date.now() - (7 * 24 * 60 * 60 * 1000); // 7 days ago
  
  // Clean up old canary deployments
  const canaryDeployments = canaryController.getAllDeployments();
  const oldCanaryDeployments = canaryDeployments.filter(d => 
    d.completedAt && d.completedAt < cutoffTime
  );
  
  // Clean up old blue-green deployments
  const blueGreenDeployments = blueGreenController.getAllDeployments();
  const oldBlueGreenDeployments = blueGreenDeployments.filter(d => 
    d.completedAt && d.completedAt < cutoffTime
  );
  
  console.log(`🧹 Cleaned up ${oldCanaryDeployments.length} canary and ${oldBlueGreenDeployments.length} blue-green deployments`);
}

// Auto-initialize in production
if (process.env.NODE_ENV === 'production') {
  initializeSafeDeployments().catch(console.error);
}

// Export deployment controllers for external use
export { canaryController, blueGreenController, errorBudgetGate };
