name: Frontend Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: site-web/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build Next.js
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: npm run build

      # OPTION A: Deploy to Vercel (automatique avec integration GitHub)
      # Rien à faire si vous utilisez l'intégration Vercel

      # OPTION B: Deploy to AWS Amplify
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #
      # - name: Deploy to Amplify
      #   run: |
      #     aws amplify start-deployment --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main

      # OPTION C: Static export + S3/CloudFront
      # - name: Export static
      #   run: npm run export
      #
      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync ./out s3://${{ secrets.S3_BUCKET_NAME }} --delete
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"