name: Build and Push of-browser-worker to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/fargate/browser-worker/**'
      - '.github/workflows/of-browser-worker-ecr.yml'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: huntaze/of-browser-worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-ECR
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tags
        id: meta
        run: |
          REG="${{ steps.login-ecr.outputs.registry }}"
          REPO="${{ env.ECR_REPOSITORY }}"
          echo "tags=${REG}/${REPO}:sha-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo -e "tags<<EOF\n${REG}/${REPO}:sha-${GITHUB_SHA}\n${REG}/${REPO}:main\nEOF" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: infra/fargate/browser-worker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
