name: UX Guard

on:
  pull_request:
    branches: [ main ]

jobs:
  ux_guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (minimal)
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Forbid 'backend' in UX
        run: bash scripts/forbid-words.sh

